### ISSUE TITLE
E-Mail address with local part containing CONTROL characters should be invalid

### ISSUE THREAD

**Issue by PascalSchumacher** [RohanNagar/jmail#236]
**Is this bug report about an incorrectly validated email address?**

- [ ] Yes

**If yes, what is the email address?**
`firstname_lastname\u0011@server.org`

I maybe wrong but I think that [RFC 822](https://www.rfc-editor.org/rfc/rfc822#section-6.1) disallows control characters in email addresses. Do newer RFCs allow them?

Sorry for using an issue for a question and thank you very much for providing JMail!

**Comment by RohanNagar** [comment]
Hey @PascalSchumacher! Thanks for the question - please feel free to ask questions on issues, it helps me know that people are still using JMail!

As for this specific question, it's a good one. I'll need some time to look into it as it's been a while since I've looked through the RFCs. I know that non-whitespace controls are allowed in quotes, but I'm not 100% sure on if they are allowed unquoted. I'm out of town for a couple of weeks but I will let you know once I get a chance to look further!

**Comment by RohanNagar** [comment]
Hi @PascalSchumacher thanks again for this issue, it is a great catch. After reading through the relevant RFCs it does indeed look like control characters are not allowed unquoted. I will work on the fix for this asap.

**Comment by PascalSchumacher** [comment]
Thank you very much! 😄 Looking forward to a release with a fix for this.
